version: '3'
services:
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  redis-data:
